#gitlabi
- name: Asennetaan policycoreutils
  dnf:
    name: policycoreutils 
    state: latest

- name: Palomuuri public - https
  firewalld:
    zone: public
    service: https
    permanent: yes
    immediate: yes
    state: enabled

- name: Asennetaan postfix  
  dnf:
    name: postfix 
    state: latest

- name: Postfix pystyyn
  service:
    name: postfix
    state: started
    enabled: yes

#itse gitlabi
- name: Lisataan gitlab repo
  shell: curl https://packages.gitlab.com/install/repositories/gitlab/gitlab-ee/script.rpm.sh | sudo bash
  args:
    warn: no

- name: Asennetaan gitlabi DNS nimella
  shell: sudo EXTERNAL_URL="https://torsala.fi" dnf install -y gitlab-ee
  args:
    warn: no

#TLS varmenteet
- name: Luetaan varmenteet muuttujiin
  include_vars: varmenteet.yml

- name: Varmenne
  copy:
    content: '{{ varmenne }}'
    dest: /etc/gitlab/ssl/torsala.fi.crt
    owner: root
    group: root
    mode: 0644

- name: Avain
  copy:
    content: '{{ avain }}'
    dest: /etc/gitlab/ssl/torsala.fi.key
    owner: root
    group: root
    mode: 0600
