- name: Valtori KT Dockeroitu Zabbix
  hosts: all
  become: yes
  become_user: root
  tasks:

#perus
  - name: Konffataan secondari palvelut kuten gateway
    shell: nmcli con mod "System eth0" ipv4.gateway 192.168.100.1;nmcli con up "System eth0"

  - name: Konffataan secondari palvelut kuten gatedns
    shell: nmcli con mod "System eth0" ipv4.dns 9.9.9.9;nmcli con up "System eth0"


#nmcli ei toimi koska vaatii paketteja, joita ei voi saada koska verkko ja dns ei toimi, korjataan syssymmalla
#  - name: Ja DNS
#    nmcli:
#      conn_name: "System eth0"
#      type: ethernet
#      dns4:
#      - 9.9.9.9
#      state: present


  - name: Paivitetaan kaikki
    yum:
      name: '*'
      state: latest


#docker alusta
  - name: Lisataan docker-ce repo
    shell: sudo dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

  - name: Sitten tykitetaan paketteja
    yum:
      name: "{{ paketit }}"
    vars:
      paketit:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
      - docker-ce
      - epel-release
      - python3
      - docker-compose

  - name: Oikkarit dockerille
    shell: sudo usermod -aG docker $(whoami)

  - name: 
    service:
      name: docker.service
      state: started
      enabled: yes

  - name: Paivitetaan pythonit 
    yum:
      name: 'python*'
      state: latest

#zabbixi

  - name: Asennetaan git
    yum:
      name: git
      state: latest

  - name: Tyokansio
    file:
      path: /opt/git/
      state: directory
      owner: root
      group: root
      mode: '0644'

  - name: Asennetaan git
    git:
      repo: https://github.com/zabbix/zabbix-docker.git
      dest: /opt/git/zabbix-docker/
      version: 5.0
  
