- name: Valtori KT Dockeroitu Zabbix
  hosts: all
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
    zabbix-versio: zabbix/zabbix-server-pgsql:centos-5.2-latest
  roles:
  - docker-pr
  - zabbix-pr