#rocket chat
- name: Asennetaan policycoreutils
  dnf:
    name: policycoreutils 
    state: latest

- name: Asennetaan python
  dnf:
    name: python3 
    state: latest

- name: Asennetaan docker-py
  shell: pip3 install docker-py


- name: Palomuuri public - http eri portissa
  firewalld:
    zone: public
    port: 443/tcp
    permanent: yes
    immediate: yes
    state: enabled
#kontti
- name: Install Rocket Chat container
  docker_container:
    name: gitlab
    image: "rocketchat:latest"
    state: started
    ports:
      - "443:443"
    restart_policy: always
