#rocket chat
- name: Asennetaan policycoreutils
  dnf:
    name: policycoreutils 
    state: latest

- name: Asennetaan python
  dnf:
    name: python3 
    state: latest


- name: Asennetaan python
  dnf:
    name: nginx 
    state: latest


- name: Asennetaan docker-py
  shell: pip3 install docker-py


#composet

- name: Tarkista versio
  command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Poista jos vaarin
  file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version is not defined

- name: Asennetaan docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 0755

#- name: Asennetaan docker-compose
#  shell: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64" -o /usr/local/bin/docker-compose

- name: Liitetaan compose pathiin
  shell: ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  ignore_errors: yes

- name: Lisaa hosti dns
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 sokkeli.testi.lol"
    state: present



- name: Tee kansio certille
  file:
    path: /opt/rocketchat/
    state: directory
    owner: root
    group: root
    mode: 0655

- name: dhparam nginx varten
  shell: openssl dhparam -out /opt/rocketchat/dhparams.pem 2048


- name: Certti - priva avain
  openssl_privatekey:
    path: /opt/rocketchat/rocketchat.key
    type: RSA

- name: Certti - csr
  openssl_csr:
    path: /opt/rocketchat/rocketchat.csr
    privatekey_path:  /opt/rocketchat/rocketchat.key
    country_name: CL
    organization_name: Valtori
    email_address: ville.vainikka@valtori.fi
    common_name: sokkeli.testi.lol
    subject_alt_name: 'DNS:sokkeli.testi.lol'

- name: Certti - certti
  openssl_certificate:
    path: /opt/rocketchat/rocketchat.crt
    privatekey_path: /opt/rocketchat/rocketchat.key
    csr_path:  /opt/rocketchat/rocketchat.csr
    provider: selfsigned

- name: Palomuuri public - http eri portissa
  firewalld:
    zone: public
    port: 443/tcp
    permanent: yes
    immediate: yes
    state: enabled


- name: Allowaan http proxytys SELinuxista
  shell: semanage permissive -a httpd_t


- name: Tee nginx conffig
  template: src=nginx.conf.j2 dest="/etc/nginx/conf.d/nginx.conf" owner=root group=root mode=0644

- name: kaynnista nginx
  service:
      name: nginx
      state: restarted
      enabled: yes

#kontit, taa pitaa korjata
#composella koska laiska

- name: Tee docker-compose filu
  template: src=docker-compose.yml.j2 dest="/opt/rocketchat/docker-compose.yml" owner=root group=root mode=0644

- name: Juoksuta compose
  shell: docker-compose -f docker-compose.yml up -d mongo
  args:
    chdir: /opt/rocketchat


- name: Juoksuta compose
  shell: docker-compose -f docker-compose.yml up -d mongo-init-replica
  args:
    chdir: /opt/rocketchat

- name: Juoksuta compose
  shell: docker-compose -f docker-compose.yml up -d rocketchat
  args:
    chdir: /opt/rocketchat
  




# - name: Asenna MongoDB kontti
#   shell: docker run --name db -d mongo:4.0 --smallfiles --replSet rs0 --oplogSize 128
#   ignore_errors: yes

# - name: Odotetaan hetki
#   pause:
#     seconds: 5

# - name: Alusta Mongo
#   shell: docker exec -ti db mongo --eval "printjson(rs.initiate())"



# - name: Install Rocket Chat container
#   docker_container:
#     name: rc
#     image: "rocketchat/rocket.chat:latest"
#     state: started
#     ports:
#       - "3000:3000"
#     restart_policy: always
#     env:
#       ROOT_URL: "http://localhost"
#       MONGO_OPLOG_URL: "mongodb://db:27017/local"
