#rocket chat
- name: Asennetaan policycoreutils
  dnf:
    name: policycoreutils 
    state: latest

- name: Asennetaan python
  dnf:
    name: python3 
    state: latest


- name: Asennetaan python
  dnf:
    name: nginx 
    state: latest


- name: Asennetaan docker-py
  shell: pip3 install docker-py

- name: Asennetaan docker-compose
  shell: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64" -o /usr/local/bin/docker-compose

- name: Asennetaan docker-compose
  shell: sudo chmod +x /usr/local/bin/docker-compose



- name: Palomuuri public - http eri portissa
  firewalld:
    zone: public
    port: 443/tcp
    permanent: yes
    immediate: yes
    state: enabled

#kontti
- name: Install Rocket Chat container
  docker_container:
    name: gitlab
    image: "rocketchat/rocket.chat:latest"
    state: started
    ports:
      - "443:443"
    restart_policy: always

