#rocket chat
- name: Asennetaan policycoreutils
  dnf:
    name: policycoreutils 
    state: latest

- name: Asennetaan python
  dnf:
    name: python3 
    state: latest


- name: Asennetaan python
  dnf:
    name: nginx 
    state: latest


- name: Asennetaan docker-py
  shell: pip3 install docker-py

#- name: Asennetaan docker-compose
#  shell: curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-Linux-x86_64" -o /usr/local/bin/docker-compose

- name: docker-compose oikkarit
  shell: chmod +x /usr/local/bin/docker-compose


- name: dhparam nginx varten
  shell: openssl dhparam -out /opt/rocketchat/dhparams.pem 2048


- name: Tee kansio certille
  file:
    path: /opt/rocketchat/
    state: directory
    owner: root
    group: root
    mode: 0655


- name: Certti - priva avain
  openssl_privatekey:
    path: /opt/rocketchat/rocketchat.key
    type: RSA

- name: Certti - csr
  openssl_csr:
    path: /opt/rocketchat/rocketchat.csr
    privatekey_path:  /opt/rocketchat/rocketchat.key
    country_name: CL
    organization_name: Valtori
    email_address: ville.vainikka@valtori.fi
    common_name: sokkeli.fi
    subject_alt_name: 'DNS:sokkeli.fi'

- name: Certti - certti
  openssl_certificate:
    path: /opt/rocketchat/rocketchat.crt
    privatekey_path: /opt/rocketchat/rocketchat.key
    csr_path:  /opt/rocketchat/rocketchat.csr
    provider: selfsigned


- name: Tee nginx conffig
  template: src=nginx.conf.j2 dest="/etc/nginx/conf.d/nginx.conf" owner=root group=root mode=0644


- name: Palomuuri public - http eri portissa
  firewalld:
    zone: public
    port: 443/tcp
    permanent: yes
    immediate: yes
    state: enabled

#kontti
- name: Install Rocket Chat container
  docker_container:
    name: rocketchat
    image: "rocketchat/rocket.chat:latest"
    state: started
    ports:
      - "443:443"
    restart_policy: always

