#perus
- name: Konffataan gateway
  shell: nmcli con mod "System eth0" ipv4.gateway 192.168.100.1;nmcli con up "System eth0"

- name: Konffataan dns server
  shell: nmcli con mod "System eth0" ipv4.dns 192.168.0.1;nmcli con up "System eth0"

- name: Konffataan dns search
  shell: nmcli con mod "System eth0" ipv4.dns-search testi.lol;nmcli con up "System eth0"


#nmcli ei toimi koska vaatii paketteja, joita ei voi saada koska verkko ja dns ei toimi, korjataan syssymmalla
#  - name: Ja DNS
#    nmcli:
#      conn_name: "System eth0"
#      type: ethernet
#      dns4:
#      - 9.9.9.9
#      state: present