#perus
- name: Konffataan secondari palvelut kuten gateway
  shell: nmcli con mod "System eth0" ipv4.gateway 192.168.100.1;nmcli con up "System eth0"

- name: Konffataan secondari palvelut kuten dns
  shell: nmcli con mod "System eth0" ipv4.dns 192.168.0.1;nmcli con up "System eth0"


#nmcli ei toimi koska vaatii paketteja, joita ei voi saada koska verkko ja dns ei toimi, korjataan syssymmalla
#  - name: Ja DNS
#    nmcli:
#      conn_name: "System eth0"
#      type: ethernet
#      dns4:
#      - 9.9.9.9
#      state: present

- name: Asennetaan aika
  dnf:
    name: chrony
    state: latest

- name: Asennetaan aika
  service:
    name: chronyd
    state: started
    enabled: yes

- name: Paivitetaan kaikki
  dnf:
    name: "*"
    state: latest

#ei valttis tarvetta tuotantoon, mutta devaukseen must
- name: Asennetaan epel, pitaa olla ennen muita koska tulevat taalta
  yum:
    name: "{{ paketit }}"
  vars:
    paketit:
    - epel-release

- name: Asennetaan diagnostiikat
  yum:
    name: "{{ paketit }}"
  vars:
    paketit:
    - net-tools
    - tcpdump
    - htop
    - iotop
