#docker alusta
# - name: Lisataan docker-ce repo
#   shell: curl https://download.docker.com/linux/centos/docker-ce.repo -o /etc/yum.repos.d/docker-ce.repo
#   args:
#     warn: no

# - name: Lisataan proxy yum conffiin
#   lineinfile: dest=/etc/yum.conf state=present regexp="proxy=http://10.88.2.10:8080"
#               insertafter=EOF line="proxy=http://10.88.2.10:8080"
#   ignore_errors: yes

#docker rhel7:lla ei ole kunnolla tuoetuna enää, vaan joudutaan kikkailemaan centos7:n kanssa, jonka polut taas menevät rhellin takia väärin
#lisaksi joudutaan varkkaamana yhteistoiminta satelliten kanssa

- name: Luetaan muuttjat
  include_vars: docker-pr.yml

- name: Dockerin repo fix
  copy:
    content: '{{ yumRepoDocker }}'
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644

- name: Epelin repo fix
  copy:
    content: '{{ yumRepoEpel }}'
    dest: /etc/yum.repos.d/epel.repo
    owner: root
    group: root
    mode: 0644


#
# ei toimi, pitaa ajaa manuaalisesti, varmaan liittyy env muuttujiin + python, mutten jaksa nyt kayttaa lisaa aikaa tahan

# - name: Konffataan subscription-managerin repot
#   shell: subscription-manager repos --disable=* --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms
#   args:
#     warn: no
#   ignore_errors: yes

#hyva idea, huono moduuli
# - name: Konffataan subscription-managerin repot1
#   community.general.rhsm_repository:
#     name: '*'
#     state: disabled

# - name: Konffataan subscription-managerin repot2
#   community.general.rhsm_repository:
#     name: 'rhel-7-server-rpm'
#     state: enabled

# - name: Konffataan subscription-managerin repot3
#   community.general.rhsm_repository:
#     name: 'rhel-7-server-extras-rpms'
#     state: enabled


- name: Konffataan yum repot
  shell: yum-config-manager --disable \* --enable docker-ce-stable --enable epel
  args:
    warn: no
  ignore_errors: yes

# - name: Sitten tykitetaan paketteja
#   yum:
#     name: "{{ paketit }}"
#   vars:
#     paketit:
#     - yum-utils
#     - device-mapper-persistent-data
#     - lvm2
# #    - https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm

- name: Asennetaa nyum-utils
  shell: yum -y install yum-utils
  args:
    warn: no
  ignore_errors: yes

- name: Asennetaan device-mapper-persistent-data
  shell: yum -y install device-mapper-persistent-data
  args:
    warn: no
  ignore_errors: yes

- name: Asennetaan lvm2
  shell: yum -y install lvm2
  args:
    warn: no
  ignore_errors: yes

- name: Asennetaan korjataan python
  shell: yum -y update-alternatives --install /usr/bin/python python /usr/bin/python3 10
  args:
    warn: no
  ignore_errors: yes

- name: Asennetaan lvm2
  shell: pip3 install docker-py  --proxy http://10.88.2.10:8080
  args:
    warn: no
  ignore_errors: yes

- name: Asennetaan docker-ce
  shell: yum -y install docker-ce
  args:
    warn: no
  ignore_errors: yes

#- name: Asennetaan docker-compose
#  shell: pip3 install docker-compose

- name: Oikkarit dockerille
  shell: usermod -aG docker $(whoami)

- name: Palomuuri docker0 - trusted
  firewalld:
    zone: trusted
    interface: docker0
    permanent: yes
    immediate: yes
    state: enabled
  vars:
    ansible_python_interpreter: '/usr/bin/python2'

- name: Palomuuri docker0 - masquerade
  firewalld:
    zone: trusted
    masquerade: yes
    permanent: yes
    immediate: yes
    state: enabled
  vars:
    ansible_python_interpreter: '/usr/bin/python2'

- name: Palomuuri public - masquerade
  firewalld:
    zone: public
    masquerade: yes
    permanent: yes
    immediate: yes
    state: enabled
  vars:
    ansible_python_interpreter: '/usr/bin/python2'

- name: Docker pystyyn
  service:
    name: docker.service
    state: started
    enabled: yes

#- name: Paivitetaan pythonit 
#  shell: yum upgrade python*
#  args:
#    warn: no