#docker alusta
- name: Lisataan docker-ce repo
  shell: curl https://download.docker.com/linux/centos/docker-ce.repo -o /etc/yum.repos.d/docker-ce.repo
  args:
    warn: no

- name: Lisataan proxy yum conffiin
  lineinfile: dest=/etc/yum.conf state=present regexp="proxy=http://10.88.2.10:8080"
              insertafter=EOF line="proxy=http://10.88.2.10:8080"
  ignore_errors: yes

#docker rhel7:lla ei ole kunnolla tuottuna enää, vaan joudutaan kikkailemaan centos7:n kanssa, jonka polut taas menevät rhellin takia väärin

- name: Luetaan varmenteet muuttujiin
  include_vars: docker-pr.yml

- name: Dockerin repo
  copy:
    content: "{{ dockerRepoConf }}"
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    groupo: root
    mode: 0755



- name: Sitten tykitetaan paketteja
  yum:
    name: "{{ paketit }}"
  vars:
    paketit:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2
    - https://download.docker.com/linux/centos/7/x86_64/stable/Packages/containerd.io-1.2.6-3.3.el7.x86_64.rpm
    - epel-release
#    - python3

- name: Asennetaan docker-ce
  shell: yum -y install docker-ce --nobest
  args:
    warn: no

#- name: Asennetaan docker-compose
#  shell: pip3 install docker-compose

- name: Oikkarit dockerille
  shell: usermod -aG docker $(whoami)

- name: Palomuuri docker0 - trusted
  firewalld:
    zone: trusted
    interface: docker0
    permanent: yes
    immediate: yes
    state: enabled

- name: Palomuuri docker0 - masquerade
  firewalld:
    zone: trusted
    masquerade: yes
    permanent: yes
    immediate: yes
    state: enabled

- name: Palomuuri public - masquerade
  firewalld:
    zone: public
    masquerade: yes
    permanent: yes
    immediate: yes
    state: enabled

- name: Docker pystyyn
  service:
    name: docker.service
    state: started
    enabled: yes

#- name: Paivitetaan pythonit 
#  shell: yum upgrade python*
#  args:
#    warn: no