- name: Luetaan varmenteet muuttujiin
  include_vars: zabbix-pr.yml

- name: Agentin tyokansio
  file:
    path: /opt/zabbix/zabbix_agent.d/
    state: directory
    owner: root
    group: root
    mode: 0655

- name: Agentin conffi
  template:
    src: zabbix_agentd.conf.j2
    dest: /opt/zabbix/zabbix_agent.d/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644

- name: Agentti
  docker_container:
    name: agentti
    image: '{{ zabbixAgenttiVersio }}'
    env: 
      ZBX_HOSTNAME="{{ ansible_facts['nodename'] }}"
      ZBX_SERVER_HOST="sauron.vyv.fi,172.17.0.0/16"
    ports:
    - "10050:10050"
    volumes:
    - /opt/zabbix/zabbix_agent.d:/etc/zabbix/zabbix_agentd.d:ro
    - /var/run/docker.sock:/var/run/docker.sock
    restart_policy: unless-stopped
    detach: yes